--- 
Site:
  nick: dataninja
  networks:
    dev:
      server: localhost
      prefix: '!'
      channels:
        - name: '#dataninja'
    freenode:
      server: 'irc.freenode.net'
      channels:
        - name: '#dataninja'
          prefix: '@'
