--- 
framework:
  Database:
    CheckSchema: 1
    Driver: Pg
    Host: localhost
    Password: 'dbpass'
    User: 'dbuser'
application:
  nick: dataninja
    dev:
      prefix: '#'
      server: 'localhost'
      channels:
        - '#dataninja'
  twitteruser: twitterme
  twitterpass: twitteryou
  clquery: 'programmer'
